### PR TITLE
Update log4net.RabbitMQ

### LINKED ISSUE #16: Upgrade to RabbitMQ Client 3.5
Do you have any plans to upgrade to RabbitMQ client 3.5?

https://groups.google.com/forum/#!topic/easynetq/Z6Z5tt-OCbk

We are getting this error:

log4net:ERROR Could not create Appender [AmqpAppender] of type [log4net.RabbitMQ.RabbitMQAppender, log4net.RabbitMQ]. Reported error follows.
System.TypeLoadException: Could not load type 'RabbitMQ.Client.Events.ConnectionShutdownEventHandler' from assembly 'RabbitMQ.Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=89e7d7c5feba84ce'.
   at log4net.RabbitMQ.RabbitMQAppenderBase.StartConnection()
   at log4net.RabbitMQ.RabbitMQAppenderBase.ActivateOptions()
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.ParseAppender(XmlElement appenderElement)
log4net:ERROR Appender named [AmqpAppender] not found.
log4net: Hierarchy Threshold []

### PR DESCRIPTION
**Pull request by nabheet**
The following updates were made in order to fix #16:
* Update target framework to 4.5.1
* Update log4net version to 1.2.13 (except the log4net.RabbitMQ.1.2.10 project - which was accidentally upgraded and then downgraded)
* Update RabbitMQ client dll to 3.5.1 and necessary code changes to allow project to compile
** ShutdownAmqp and OnModelShutdown function signatures were changed to comply with the new event handler changes in the RabbitMQ client.
* recreated log4net.RabbitMQ.SampleWeb as the latest MVC project
* fixed a bug where priority was not being retrieved from Message Properties, and fixed associated unit test.

I have tested the sample web and listener projects with these updates against RabbitMQ server version 3.2.2 and confirm that it works.

However, I am not sure how to test the log4net.RabbitMQ.1.2.10 project. Please advise. (Or I can ignore it. :-))

Thank you.

### CODE REVIEW

**Comment by haf** [comment]
Could you properly link these commits to your github profile by setting your git e-mail?

How does 4.5.1 work with mono?

Could you make RMQ a Paket dependency rather than a binary file?

Nice work otherwise.

**Comment by nabheet** [comment]
Mono website says that .Net 4.5 is good: http://www.mono-project.com/docs/about-mono/compatibility/.

So I assume 4.5.1 may not be good, so I can change it back. And I will investigate editing the commits for my email.

However, I do not understand what you mean by making RabbitMQ as "Packet dependency". I added it as a Nuget package. Is that not enough? Please provide guidance.

**Comment by nabheet** [comment]
Just pushed a commit:
* Downgrade target framework for all projects from .net 4.5.1 to 4.5.
* linked commit to primary email in Github profile, also added other email to github profile rather than editing commits. I tried editing author in commits using script at https://help.github.com/articles/changing-author-info/ and it ended up redoing every commit. I did not want that, so I just added the email to my profile for now.

Still waiting on clarification on "RMQ as Paket Dependency". Otherwise, if these changes are acceptable to you, can you please merge this request and generate the nuget package? I need to pull them into our dependent codebase.

**Comment by haf** [comment]
Those changes are just fine, thanks!

The last 'rmq as paket dependency' ([Paket](https://fsprojects.github.io/Paket/)) is so that we don't have to source-control binaries. It also makes downloading of the repo much quicker.

Basically;

```
paket convert-from-nuget
paket install
git add .
git commit -am 'using paket'
```

**Comment by nabheet** [comment]
I just tried it and I find this really interesting. However, it seems that paket only allows one version of log4net in the solution whereas we have two versions: 2.0.3 and 1.2.10. 

I think we have two options:
* do not use paket
* use paket but delete/remove the log4net.RabbitMQ.1.2.10 project from the solution
* any other option you can suggest

How would you suggest that I proceed?

**Comment by haf** [comment]
I think you could move the older version to its own solution folder and do a `paket convert-from-nuget` on it on its own.

**Comment by haf** [comment]
But yeah, remove the old project from the 'normal compilation, imo'. And add a README in its folder stating this, linking to this thread.

**Comment by nabheet** [comment]
Sounds good. Here are the tasks as I understand them:
* change build configuration to not build log4net.RabbitMQ.1.2.10 project
* move project into physical folder called obsolete (or something)
* add solution folder to solution called obsolete
* move the project to this solution folder
* add README.md in obsolete folder that states that this project was moved and disabled from the build. For details refer to this thread: <http link>.

Do you concur?

**Comment by haf** [comment]
Yes, I concur.

**Comment by nabheet** [comment]
Anyways, I think I am done. here is what I did:
* removed project from solution, moved it to obsolete folder outside of src because paket was still updating references.
* I had to commit the paket.exe to source control because without it I was getting file lock errors when building solution for the first time. https://github.com/fsprojects/Paket/issues/244 and https://github.com/fsprojects/VisualFSharpPowerTools/issues/824.
* updated all the references to use paket.

**Comment by haf** [comment]
For your master, can't compile, getting:

```
bundle exec rake
xbuild /verbosity:minimal src/log4net.RabbitMQ.sln
XBuild Engine Version 12.0
Mono, Version 3.12.1.0
Copyright (C) 2005-2013 Various Mono authors
		Configuration: Debug Platform: AnyCPU
	Configuration: Debug Platform: x86
Configuration: Debug Platform: AnyCPU
Configuration: Debug Platform: AnyCPU
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/xbuild/12.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Web.Entity' not resolved
I 2015-04-05T11:42:06.108115+02:00: while building nuspec for proj: log4net.RabbitMQ, file: /Users/henrik.feldt/dev/haf/log4net.RabbitMQ/src/log4net.RabbitMQ/bin/Debug/log4net.RabbitMQ.xml => lib/net40 not found, removing from nuspec [nuget model: package]
I 2015-04-05T11:42:06.108849+02:00: while building nuspec for proj: log4net.RabbitMQ, file: /Users/henrik.feldt/dev/haf/log4net.RabbitMQ/src/log4net.RabbitMQ/bin/Debug/log4net.RabbitMQ.config => lib/net40 not found, removing from nuspec [nuget model: package]
mono /Users/henrik.feldt/dev/haf/log4net.RabbitMQ/src/.nuget/NuGet.exe Pack -OutputDirectory /Users/henrik.feldt/dev/haf/log4net.RabbitMQ/build/pkg /Users/henrik.feldt/dev/haf/log4net.RabbitMQ/src/log4net.RabbitMQ/log4net.RabbitMQAppender.nuspec
Cannot open assembly '/Users/henrik.feldt/dev/haf/log4net.RabbitMQ/src/.nuget/NuGet.exe': No such file or directory.
```

**Comment by haf** [comment]
Please remove UpgradeLog from the index.

**Comment by haf** [comment]
So for the compilation error; it's because NuGet.exe is no longer in the solution; you have two choices; either add NuGet.CommandLine as a paket dependency and change its path in the Rakefile, or use `paket pack`.

**Comment by nabheet** [comment]
My apologies, I saw the rakefile but didn't investigate what it was doing.

I am getting this error and I can't read it. I assume that because I don't have your language pack, I can get the correct error message:

$ bundle exec rake --trace
DL is deprecated, please use Fiddle
** Invoke default (first_time)
** Invoke create_nugets (first_time)
** Invoke build/pkg (first_time, not_needed)
** Invoke versioning (first_time)
** Execute versioning
** Invoke build (first_time)
** Invoke versioning
** Invoke restore (first_time)
** Execute restore
** Execute build
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe /verbosity:minimal src\log4net.RabbitMQ.sln
Microsoft (R) Build Engine version 4.0.30319.33440
[Microsoft .NET Framework, version 4.0.30319.34014]
Copyright (C) Microsoft Corporation. All rights reserved.

  Paket version 0.38.4.0
  0 seconds - ready.
  log4net.RabbitMQ -> c:\fswgit\log4net.RabbitMQ\src\log4net.RabbitMQ\bin\Debug\log4net.RabbitMQ.dll
  Paket version 0.38.4.0
  0 seconds - ready.
  log4net.RabbitMQ.Tests -> c:\fswgit\log4net.RabbitMQ\src\log4net.RabbitMQ.Tests\bin\Debug\log4net.RabbitMQ.Tests.dll
  Paket version 0.38.4.0
  0 seconds - ready.
  log4net.RabbitMQ.Listener -> c:\fswgit\log4net.RabbitMQ\src\samples\log4net.RabbitMQ.Listener\bin\Debug\log4net.RabbitMQ.Listener.exe
c:\fswgit\log4net.RabbitMQ\src\samples\log4net.RabbitMQ.SampleWeb\log4net.RabbitMQ.SampleWeb.csproj(188,3): error MSB4019: The imported projreackte  "aCb:o\rPtreodg!r
m AFliblaecso r(ex:8:6C)o\mMmSaBnudiFladi\lMeidcErrorsoorf:t \CVoimsmuaanldS tfuadiiloe\dv 1w1i.t0h\ WsetbaAtpupsl i(c1at)i:o
s \ MCi:c\rWoisonfdto.wWse\bMAipcprolsiocfatt.iNoEnT.\tFarrgaemtse"w owrka\sv 4n.o0t. 3f0o3u1n9d\.m sCbouniflidr.m etxhea t/ vtehreb opsaitthy :imni ntihmea l< Ismrpco\rlto>g 4dneectl.aRarabtbiiotMnQ .issl nc
1Mrieccrt,o saondf t th(aRt) t Bheu ilfdi lEe negixnei vsetrss ioonn  d4i.0s.3k0.3
33440
[Microsoft .NET Framework, version 4.0.30319.34014]
Copyright (C) Microsoft Corporation. All rights reserved.

  Paket version 0.38.4.0
  0 seconds - ready.
  log4net.RabbitMQ -> c:\fswgit\log4net.RabbitMQ\src\log4net.RabbitMQ\bin\Debug\log4net.RabbitMQ.dll
  Paket version 0.38.4.0
  0 seconds - ready.
  log4net.RabbitMQ.Tests -> c:\fswgit\log4net.RabbitMQ\src\log4net.RabbitMQ.Tests\bin\Debug\log4net.RabbitMQ.Tests.dll
  Paket version 0.38.4.0
  0 seconds - ready.
  log4net.RabbitMQ.Listener -> c:\fswgit\log4net.RabbitMQ\src\samples\log4net.RabbitMQ.Listener\bin\Debug\log4net.RabbitMQ.Listener.exe
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/albacore-2.0.0/lib/albacore/cross_platform_cmd.rb:258:in `raise_failure'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/albacore-2.0.0/lib/albacore/cross_platform_cmd.rb:237:in `block in handler_with_message'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/albacore-2.0.0/lib/albacore/cross_platform_cmd.rb:110:in `call'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/albacore-2.0.0/lib/albacore/cross_platform_cmd.rb:110:in `block in system'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/albacore-2.0.0/lib/albacore/cross_platform_cmd.rb:242:in `handle_not_found'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/albacore-2.0.0/lib/albacore/cross_platform_cmd.rb:87:in `system'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/albacore-2.0.0/lib/albacore/task_types/build.rb:20:in `execute'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/albacore-2.0.0/lib/albacore/task_types/build.rb:202:in `execute'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/albacore-2.0.0/lib/albacore/dsl.rb:45:in `block in build'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
c:/tools/ruby215/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:199:in `each'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:199:in `invoke_prerequisites'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
c:/tools/ruby215/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:199:in `each'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:199:in `invoke_prerequisites'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
c:/tools/ruby215/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
c:/tools/ruby215/lib/ruby/gems/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
c:/tools/ruby215/bin/rake:23:in `load'
c:/tools/ruby215/bin/rake:23:in `<main>'
Tasks: TOP => default => create_nugets => build

**Comment by haf** [comment]
Just run the command printed above the error; msbuild.exe.

**Comment by nabheet** [comment]
so now I think I have reached the limits of my knowledge and skills.

I am getting "symbols not configured for generation, use Config#gen_symbols to do so [nugets pack: cmd] ". 

I don't know what to do next.

$ bundle exec rake
DL is deprecated, please use Fiddle                                                                                                                                                                  
mkdir -p build/pkg                                                                                                                                                                                   
cd .\src && .paket\paket.exe restore                                                                                                                                                                 
Paket version 0.38.4.0                                                                                                                                                                               
Microsoft.AspNet.Web.Optimization 1.1.3 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\Microsoft.AspNet.Web.Optimization                                                                        
Antlr 3.4.1.9004 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\Antlr                                                                                                                           
jQuery.Validation 1.11.1 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\jQuery.Validation                                                                                                       
Microsoft.AspNet.Razor 3.2.2 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\Microsoft.AspNet.Razor                                                                                              
Microsoft.AspNet.Mvc 5.2.2 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\Microsoft.AspNet.Mvc                                                                                                  
bootstrap 3.0.0 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\bootstrap                                                                                                                        
jQuery 1.10.2 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\jQuery                                                                                                                             
Microsoft.Web.Infrastructure 1.0.0.0 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\Microsoft.Web.Infrastructure                                                                                
Modernizr 2.6.2 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\Modernizr                                                                                                                        
Microsoft.jQuery.Unobtrusive.Validation 3.2.2 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\Microsoft.jQuery.Unobtrusive.Validation                                                            
NUnit 2.6.4 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\NUnit                                                                                                                                
Microsoft.AspNet.WebPages 3.2.2 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\Microsoft.AspNet.WebPages                                                                                        
Respond 1.2.0 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\Respond                                                                                                                            
RabbitMQ.Client 3.5.1 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\RabbitMQ.Client                                                                                                            
NuGet.CommandLine 2.8.3 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\NuGet.CommandLine                                                                                                        
SharpTestsEx 1.1.1 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\SharpTestsEx                                                                                                                  
WebGrease 1.5.2 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\WebGrease                                                                                                                        
log4net 2.0.3 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\log4net                                                                                                                            
Newtonsoft.Json 6.0.4 unzipped to c:\fswgit\log4net.RabbitMQ\src\packages\Newtonsoft.Json                                                                                                            
1 second - ready.                                                                                                                                                                                    
INFO: Could not find files for the given pattern(s).                                                                                                                                                 
INFO: Could not find files for the given pattern(s).                                                                                                                                                 
INFO: Could not find files for the given pattern(s).                                                                                                                                                 
INFO: Could not find files for the given pattern(s).                                                                                                                                                 
C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe /verbosity:minimal /property:Configuration=Release src\log4net.RabbitMQ.sln                                                                
Microsoft (R) Build Engine version 4.0.30319.33440                                                                                                                                                   
[Microsoft .NET Framework, version 4.0.30319.34014]                                                                                                                                                  
Copyright (C) Microsoft Corporation. All rights reserved.                                                                                                                                            
                                                                                                                                                                                                     
  Paket version 0.38.4.0                                                                                                                                                                             
  0 seconds - ready.                                                                                                                                                                                 
ExchangeBinding.cs(19,16): warning CS1591: Missing XML comment for publicly visible type or member 'log4net.RabbitMQ.ExchangeBinding.ExchangeBinding()' [c:\fswgit\log4net.RabbitMQ\src\log4net.Rabbi
tMQ\log4net.RabbitMQ.csproj]                                                                                                                                                                         
RabbitMQAppender.cs(5,18): warning CS1591: Missing XML comment for publicly visible type or member 'log4net.RabbitMQ.RabbitMQAppender' [c:\fswgit\log4net.RabbitMQ\src\log4net.RabbitMQ\log4net.Rabbi
tMQ.csproj]                                                                                                                                                                                          
RabbitMQAppenderBase.cs(124,32): warning CS1574: XML comment on 'log4net.RabbitMQ.RabbitMQAppenderBase.SetProtocol(string)' has cref attribute 'Protocols.Lookup' that could not be resolved [c:\fswg
it\log4net.RabbitMQ\src\log4net.RabbitMQ\log4net.RabbitMQ.csproj]                                                                                                                                    
RabbitMQAppenderBase.cs(224,33): warning CS1591: Missing XML comment for publicly visible type or member 'log4net.RabbitMQ.RabbitMQAppenderBase.Append(log4net.Core.LoggingEvent)' [c:\fswgit\log4net
.RabbitMQ\src\log4net.RabbitMQ\log4net.RabbitMQ.csproj]                                                                                                                                              
RabbitMQAppenderBase.cs(315,35): warning CS1591: Missing XML comment for publicly visible type or member 'log4net.RabbitMQ.RabbitMQAppenderBase.Format(log4net.Core.LoggingEvent)' [c:\fswgit\log4net
.RabbitMQ\src\log4net.RabbitMQ\log4net.RabbitMQ.csproj]                                                                                                                                              
RabbitMQAppenderBase.cs(341,30): warning CS1591: Missing XML comment for publicly visible type or member 'log4net.RabbitMQ.RabbitMQAppenderBase.ActivateOptions()' [c:\fswgit\log4net.RabbitMQ\src\lo
g4net.RabbitMQ\log4net.RabbitMQ.csproj]                                                                                                                                                              
RabbitMQAppenderBase.cs(403,33): warning CS1591: Missing XML comment for publicly visible type or member 'log4net.RabbitMQ.RabbitMQAppenderBase.OnClose()' [c:\fswgit\log4net.RabbitMQ\src\log4net.Ra
bbitMQ\log4net.RabbitMQ.csproj]                                                                                                                                                                      
RabbitMQAppenderBase.cs(477,33): warning CS1591: Missing XML comment for publicly visible type or member 'log4net.RabbitMQ.RabbitMQAppenderBase.Debug(string, params object[])' [c:\fswgit\log4net.Ra
bbitMQ\src\log4net.RabbitMQ\log4net.RabbitMQ.csproj]                                                                                                                                                 
RabbitMQAppenderBase.cs(170,23): warning CS1591: Missing XML comment for publicly visible type or member 'log4net.RabbitMQ.RabbitMQAppenderBase.AppId' [c:\fswgit\log4net.RabbitMQ\src\log4net.Rabbit
MQ\log4net.RabbitMQ.csproj]                                                                                                                                                                          
RabbitMQAppenderBase.cs(398,29): warning CS1591: Missing XML comment for publicly visible type or member 'log4net.RabbitMQ.RabbitMQAppenderBase.Ssl' [c:\fswgit\log4net.RabbitMQ\src\log4net.RabbitMQ
\log4net.RabbitMQ.csproj]                                                                                                                                                                            
RabbitMQAppender.cs(6,35): warning CS1591: Missing XML comment for publicly visible type or member 'log4net.RabbitMQ.RabbitMQAppender.Format(log4net.Core.LoggingEvent)' [c:\fswgit\log4net.RabbitMQ\
src\log4net.RabbitMQ\log4net.RabbitMQ.csproj]                                                                                                                                                        
RabbitMQAppender.cs(10,33): warning CS1591: Missing XML comment for publicly visible type or member 'log4net.RabbitMQ.RabbitMQAppender.Debug(string, params object[])' [c:\fswgit\log4net.RabbitMQ\sr
c\log4net.RabbitMQ\log4net.RabbitMQ.csproj]                                                                                                                                                          
  log4net.RabbitMQ -> c:\fswgit\log4net.RabbitMQ\src\log4net.RabbitMQ\bin\Release\log4net.RabbitMQ.dll                                                                                               
  Paket version 0.38.4.0                                                                                                                                                                             
  0 seconds - ready.                                                                                                                                                                                 
  log4net.RabbitMQ.Tests -> c:\fswgit\log4net.RabbitMQ\src\log4net.RabbitMQ.Tests\bin\Release\log4net.RabbitMQ.Tests.dll                                                                             
  Paket version 0.38.4.0                                                                                                                                                                             
  0 seconds - ready.                                                                                                                                                                                 
  log4net.RabbitMQ.Listener -> c:\fswgit\log4net.RabbitMQ\src\samples\log4net.RabbitMQ.Listener\bin\Release\log4net.RabbitMQ.Listener.exe                                                            
I 2015-04-05T09:39:59.328040-06:00: while building nuspec for proj: log4net.RabbitMQ, file: c:/fswgit/log4net.RabbitMQ/src/log4net.RabbitMQ/bin/Debug/log4net.RabbitMQ.dll => lib\net40 not found, re
moving from nuspec [nuget model: package]                                                                                                                                                            
I 2015-04-05T09:39:59.332092-06:00: while building nuspec for proj: log4net.RabbitMQ, file: c:/fswgit/log4net.RabbitMQ/src/log4net.RabbitMQ/bin/Debug/log4net.RabbitMQ.xml => lib\net40 not found, re
moving from nuspec [nuget model: package]                                                                                                                                                            
I 2015-04-05T09:39:59.347720-06:00: while building nuspec for proj: log4net.RabbitMQ, file: c:/fswgit/log4net.RabbitMQ/src/log4net.RabbitMQ/bin/Debug/log4net.RabbitMQ.config => lib\net40 not found,
 removing from nuspec [nuget model: package]                                                                                                                                                         
c:\fswgit\log4net.RabbitMQ\src\packages\NuGet.CommandLine\tools\NuGet.exe Pack -OutputDirectory c:/fswgit/log4net.RabbitMQ/build/pkg c:/fswgit/log4net.RabbitMQ/src/log4net.RabbitMQ/log4net.RabbitMQ
Appender.nuspec                                                                                                                                                                                      
Attempting to build package from 'log4net.RabbitMQAppender.nuspec'.                                                                                                                                  
Successfully created package 'c:/fswgit/log4net.RabbitMQ/build/pkg\log4net.RabbitMQAppender.1.2.0.nupkg'.                                                                                            
                                                                                                                                                                                                     
WARNING: 4 issue(s) found with package 'log4net.RabbitMQAppender'.                                                                                                                                   
                                                                                                                                                                                                     
Issue: Assembly outside lib folder.                                                                                                                                                                  
Description: The assembly 'bin\Release\log4net.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.                            
Solution: Move it into the 'lib' folder if it should be referenced.                                                                                                                                  
                                                                                                                                                                                                     
Issue: Assembly outside lib folder.                                                                                                                                                                  
Description: The assembly 'bin\Release\log4net.RabbitMQ.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.                   
Solution: Move it into the 'lib' folder if it should be referenced.                                                                                                                                  
                                                                                                                                                                                                     
Issue: Assembly outside lib folder.                                                                                                                                                                  
Description: The assembly 'bin\Release\RabbitMQ.Client.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.                    
Solution: Move it into the 'lib' folder if it should be referenced.                                                                                                                                  
                                                                                                                                                                                                     
Issue: Assembly outside lib folder.                                                                                                                                                                  
Description: The assembly 'obj\Release\log4net.RabbitMQ.dll' is not inside the 'lib' folder and hence it won't be added as referencI 2015-04-05T09:40:00.039789-06:00: symbols not configured for gen
eration, use Config#gen_symbols to do so [nugets pack: cmd]                                                                                                                                          
e when the package is installed into a project.                                                                                                                                                      
Solution: Move it into the 'lib' folder if it should be referenced.

**Comment by haf** [comment]
@nabheet awesome job, thank you!

**Comment by haf** [comment]
v1.3.0 released.

**Comment by nabheet** [comment]
Thank you!

**Pull request merged**
